language: node_js
node_js:
 - "node"
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database thewall_test;' -U postgres
  - psql -c 'create database thewall;' -U postgres
  - npm i knex -g
  - npm install
script:
  - npm run test
  - npm run coverage
  - npm run linter
deploy:
  - provider: script
    skip_cleanup: true
    script: sh .travis/pu.sh
    on:
      branch: master
      tags: false
  - provider: npm
    email: antonio.fontainecorrea@gmail.com
    api_key: $NPM_TOKEN
    edge: true
    on:
      branch: master
