language: node_js
node_js:
 - "node"
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database thewall_test;' -U postgres
  - psql -c 'create database thewall;' -U postgres
  - npm i knex -g
script:
  - npm run test
  - npm run coverage
  - npm run linter
